export const product = [
    {
      id: 1,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: 'Code - Y523201',
      categories: ['featured products'],
      price: 53.00,
      olderPrice: null,
      rating: 5,
      ratingCount: 88,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-1_i0v1dc.png',
    },
    {
      id: 2,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: 'Code - Y523201',
      categories: ['featured products'],
      price: 42.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611820/product-2_p36bkg.png',
    },
    {
      id: 3,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: 'Code - Y523201',
      categories: ['featured products'],
      price: 40.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736612662/product-3_czpjfd.png',
    },
    {
      id: 4,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: 'Code - Y523201',
      categories: ['featured products'],
      price: 45.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736612830/product-4_kjx31o.png',
    },
    {
      id: 5,
      name: 'Comfort Handy Craft',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['latest products'],
      price: 42.00,
      olderPrice: 65.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613033/product-5_mzt2c0.png',
    },
    {
      id: 6,
      name: 'Comfort Handy Craft',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['latest products'],
      price: 42.00,
      olderPrice: 65.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: true,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613170/product-6_aj2jyo.png',
    },
    {
      id: 7,
      name: 'Comfort Handy Craft',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['latest products'],
      price: 42.00,
      olderPrice: 65.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-1_i0v1dc.png',
    },
    {
      id: 8,
      name: 'Comfort Handy Craft',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['latest products'],
      price: 42.00,
      olderPrice: 65.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613348/product-18_utcoji.png',
    },
    {
      id: 9,
      name: 'Comfort Handy Craft',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['latest products'],
      price: 42.00,
      olderPrice: 65.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613452/product-19_hb4dsk.png',
    },
    {
      id: 10,
      name: 'Comfort Handy Craft',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['latest products'],
      price: 42.00,
      olderPrice: 65.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-4_kjx31o.png',
    },
    {
      id: 11,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['trending products'],
      price: 26.00,
      olderPrice: 42.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-9_kfei7m.png',
    },
    {
      id: 12,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['trending products'],
      price: 26.00,
      olderPrice: 42.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-10_thjb6t.png',
    },
    {
      id: 13,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['trending products'],
      price: 26.00,
      olderPrice: 42.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736614001/product-13_wy3fbi.png',
    },
    {
      id: 14,
      name: 'Cantilever chair',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['trending products'],
      price: 26.00,
      olderPrice: 42.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613452/product-19_hb4dsk.png',
    },
    {
      id: 15,
      name: '23% off in all products',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['trending products'],
      price: 26.00,
      olderPrice: 42.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736614195/product-24_mhglka.png',
    },
    {
      id: 15,
      name: '23% off in all products',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
      sku: null,
      categories: ['trending products'],
      price: 26.00,
      olderPrice: 42.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736614296/product-25_yppoja.png',
    },
    {
      id: 16,
      name: 'Executive Seat chair',
      description: 'null',
      sku: null,
      categories: ['trending products'],
      price: null,
      olderPrice: 32.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-14_wnbe1f.png',
    },
    {
      id: 17,
      name: 'Executive Seat chair',
      description: 'null',
      sku: null,
      categories: ['trending products'],
      price: null,
      olderPrice: 32.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-15_de6ssu.png',
    },
    {
      id: 18,
      name: 'Executive Seat chair',
      description: 'null',
      sku: null,
      categories: ['trending products'],
      price: null,
      olderPrice: 32.00,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-16_rnoqsv.png',
    },
    {
      id: 20,
      name: 'Mini LCW Chair',
      description: null,
      sku: null,
      categories: ['top categories'],
      price: 56.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-17_ehrrm7.png',
    },
    {
      id: 21,
      name: 'Mini LCW Chair',
      description: null,
      sku: null,
      categories: ['top categories'],
      price: 56.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-1_i0v1dc.png',
    },
    {
      id: 22,
      name: 'Mini LCW Chair',
      description: null,
      sku: null,
      categories: ['top categories'],
      price: 56.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-9_kfei7m.png',
    },
    {
      id: 23,
      name: 'Mini LCW Chair',
      description: null,
      sku: null,
      categories: ['top categories'],
      price: 56.00,
      olderPrice: null,
      rating: null,
      ratingCount: null,
      colors: ['blue', 'red', 'green', 'blue'],
      sale: false,
      image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736618925/product-17_ehrrm7.png',
    },
  ];