import { NextResponse } from 'next/server';

const product = [
  {
    id: 1,
    name: 'Cantilever chair',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: 'Code - Y523201',
    categories: ['featured products'],
    price: 53.00,
    olderPrice: null,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-1_i0v1dc.png',
  },
  {
    id: 2,
    name: 'Cantilever chair',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: 'Code - Y523201',
    categories: ['featured products'],
    price: 42.00,
    olderPrice: null,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611820/product-2_p36bkg.png',
  },
  {
    id: 3,
    name: 'Cantilever chair',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: 'Code - Y523201',
    categories: ['featured products'],
    price: 40.00,
    olderPrice: null,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736612662/product-3_czpjfd.png',
  },
  {
    id: 4,
    name: 'Cantilever chair',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: 'Code - Y523201',
    categories: ['featured products'],
    price: 45.00,
    olderPrice: null,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736612830/product-4_kjx31o.png',
  },
  {
    id: 5,
    name: 'Comfort Handy Craft',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['latest products'],
    price: 42.00,
    olderPrice: 65.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613033/product-5_mzt2c0.png',
  },
  {
    id: 6,
    name: 'Comfort Handy Craft',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['latest products'],
    price: 42.00,
    olderPrice: 65.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: true,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736613170/product-6_aj2jyo.png',
  },
  {
    id: 7,
    name: 'Comfort Handy Craft',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['latest products'],
    price: 42.00,
    olderPrice: 65.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-1_i0v1dc.png',
  },
  {
    id: 8,
    name: 'Comfort Handy Craft',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['latest products'],
    price: 42.00,
    olderPrice: 65.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-7_aj2jyo.png',
  },
  {
    id: 9,
    name: 'Comfort Handy Craft',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['latest products'],
    price: 42.00,
    olderPrice: 65.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-8_aj2jyo.png',
  },
  {
    id: 10,
    name: 'Comfort Handy Craft',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['latest products'],
    price: 42.00,
    olderPrice: 65.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-4_kjx31o.png',
  },
  {
    id: 11,
    name: 'Cantilever chair',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['trending products'],
    price: 26.00,
    olderPrice: 42.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-9_kfei7m.png',
  },
  {
    id: 12,
    name: 'Cantilever chair',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tellus porttitor purus, et volutpat sit.',
    sku: null,
    categories: ['trending products'],
    price: 26.00,
    olderPrice: 42.00,
    rating: null,
    ratingCount: null,
    colors: ['blue', 'red', 'green', 'blue'],
    sale: false,
    image: 'https://res.cloudinary.com/dqpct16iq/image/upload/v1736611722/product-10_thjb6t.png',
  },
];

// Handle GET requests
export async function GET() {
  return NextResponse.json(product); // Return JSON response
}

